# Generated by Django 3.0.6 on 2020-07-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='first_name',
            new_name='winner_name',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='second_name',
        ),
    ]
