# Generated by Django 3.0.6 on 2020-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('USER', 'USER'), ('PANELIST', 'PANELIST')], default='USER', max_length=50),
        ),
    ]
