# Generated by Django 3.0.6 on 2020-06-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200628_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
