# Generated by Django 3.0.6 on 2020-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=100)),
                ('position', models.IntegerField(choices=[(1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD')])),
            ],
        ),
    ]
