# Generated by Django 3.0.6 on 2020-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
