# Generated by Django 3.0.6 on 2020-05-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=300)),
                ('nominee', models.CharField(max_length=50, null=True)),
                ('reason', models.TextField(max_length=1000)),
                ('impact', models.TextField(max_length=1000)),
                ('username', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
