# Generated by Django 3.0.6 on 2020-05-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_nominee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='nominee',
            new_name='nominee_name',
        ),
    ]
