# Generated by Django 3.0.6 on 2020-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200526_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='nominee_name',
            field=models.CharField(default='Nominee', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='username',
            field=models.CharField(default='CurrentUser', max_length=200, null=True),
        ),
    ]
