# Generated by Django 3.0.6 on 2020-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200526_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='session',
            field=models.CharField(default='thissession', max_length=50),
        ),
    ]
